Repository atomist/sdm-pack-analysis, pull requests merged in 2019-04, with the labels that each got.

#9 Add support for sending messages from a Project Analysis
  index.ts
  lib/analysis/Interpretation.ts
  lib/analysis/ProjectAnalyzer.ts
  lib/analysis/support/DefaultProjectAnalyzerBuilder.ts
  lib/analysis/support/messageGoal.ts
  lib/pack.ts
  package-lock.json
  package.json
  test/analysis/support/scoring.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added, enhancement

#11 Introduce project classification
  index.ts
  lib/analysis/Interpretation.ts
  lib/analysis/ProjectAnalysis.ts
  lib/analysis/ProjectAnalyzer.ts
  lib/analysis/TechnologyScanner.ts
  lib/analysis/support/DefaultProjectAnalyzerBuilder.ts
  lib/analysis/support/messageGoal.ts
  lib/analysis/support/projectAnalysisUtils.ts
  test/analysis/projectAnalyzer.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added, enhancement

#19 Analysis is now also available on RunCondition
  lib/analysis/ProjectAnalysis.ts
  lib/analysis/ProjectAnalyzer.ts
  lib/analysis/support/DefaultProjectAnalyzerBuilder.ts
  lib/analysis/support/messageGoal.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added

#22 Expose Uhura goal status on full analysis
  lib/analysis/ProjectAnalysis.ts
  lib/analysis/support/DefaultProjectAnalyzerBuilder.ts
  lib/analysis/support/messageGoal.ts
  test/analysis/projectAnalyzer.test.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:added

#23 Add fingerprint support
  lib/analysis/ProjectAnalysis.ts
  lib/analysis/TechnologyScanner.ts
  lib/analysis/support/DefaultProjectAnalyzerBuilder.ts
  test/analysis/projectAnalyzer.test.ts
  test/analysis/support/projectAnalysisUtils.test.ts
Labels: auto-merge-method:squash, auto-merge:on-check-success, changelog:added
